helm template generation
roost-io/voting_app pull request #50
Opened 2022-05-03 09:57 UTC by wepull

2022-05-04 11:32 UTC, harishagrawal approved these changes

2022-05-04 13:56 UTC, mgdevstack requested changes

2022-05-04 13:56 UTC, mgdevstack commented on Makefile
>  endif
It's better to setup ${DOCKER_HOST_ARG} once around top of the script and use in necessary targets.

```
DOCKER_HOST_ARG=""
ifdef DOCKER_HOST
        DOCKER_HOST_ARG="-H ${DOCKER_HOST}"
endif
```

```suggestion
	docker ${DOCKER_HOST_ARG} build -t ${BALLOT_IMG}:${IMAGE_TAG} -f ballot/Dockerfile ballot
```

2022-05-04 14:03 UTC, mgdevstack requested changes
README.md should be updated to let user know that `make generate` command can be used to generate deployment YAMLs for all services individually (if they wish to deploy single microservice)

2022-07-28 07:47 UTC, harishagrawal commented on Makefile
> +	docker ${DOCKER_HOST_ARG} build -t ${BALLOT_IMG}:${IMAGE_TAG} -f ballot/Dockerfile ballot
where are we defining DOCKER_HOST_ARG?
ifdef does not have a closre

2022-07-28 09:11 UTC, closed without merging